name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image locally
      run: docker build . -t my-image-name:latest

    - name: Debug - List Docker images
      run: docker images

    - name: Tag and Push the Docker image
      run: |
        echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
        docker tag my-image-name:latest $DOCKER_HUB_USERNAME/my-image-name:latest
        docker push $DOCKER_HUB_USERNAME/my-image-name:latest
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
